### ISSUE TITLE
Imposible to integrate with amethyst?

### ISSUE THREAD

**Issue by jmwielandt** [bamling/specs-physics#29] opened 2020-01-02 21:06 UTC
Hi, 

I'm developing a little game with amethyst and I wanted to use specs-physics to manage collitions but, when I try to integrate your lib, a lot of problems start appearing.

Following [this guide](https://book.amethyst.rs/stable/controlling_system_execution/state-specific_dispatcher.html) and based on your own code, i've made this:

```rust
#[derive(Default)]
pub struct OverworldState<'a, 'b> {
    dispatcher: Option<Dispatcher<'a, 'b>>,
}

impl<'a, 'b> SimpleState for OverworldState<'a, 'b> {
    fn on_start(&mut self, data: StateData<'_, GameData<'_, '_>>) {
        let world = data.world;

        let mut dispatcher_builder = DispatcherBuilder::new();
        register_physics_systems::<f32, SimplePosition<f32>>(&mut dispatcher_builder);
        let mut dispatcher = dispatcher_builder
            .with_pool((*world.read_resource::<ArcThreadPool>()).clone())
            .build();
        dispatcher.setup(world);
        self.dispatcher = Some(dispatcher);
        ...
```

And with a `cargo check` test, it throws me this error: 

```
error[E0308]: mismatched types
  --> src\overworld.rs:51:62
   |
51 |         register_physics_systems::<f32, SimplePosition<f32>>(&mut dispatcher_builder);
   |                                                              ^^^^^^^^^^^^^^^^^^^^^^^ expected struct `shred::dispatch::builder::DispatcherBuilder`, found struct `overworld::amethyst::specs::DispatcherBuilder`
   |
   = note: expected type `&mut shred::dispatch::builder::DispatcherBuilder<'_, '_>`
              found type `&mut overworld::amethyst::specs::DispatcherBuilder<'_, '_>`
note: Perhaps two different versions of crate `shred` are being used?
  --> src\overworld.rs:51:62
   |
51 |         register_physics_systems::<f32, SimplePosition<f32>>(&mut dispatcher_builder);
   |                                                              ^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

And I can't use your dispatcher because is private.

In this situation, I really don't know what can I do, except peck your lib and add it as part of my code, but it isn't the idea.

This crate is under Amethyst's github, so... the most obvius is that there is something that I'm not seeing.

Thanks!

**Comment by topokel** [comment] 2020-01-02 21:50
This is a specs version mismatch. The problem is not that specs-physics is not exposing the specs crate it uses, it's that you're using a different version than specs-physics. Please note 0.4.0 will be released soon with an entirely revised API #23

**Closed as completed** 2020-01-02 21:50 UTC
